---
project:
  title: My Pushpin project
  description: Title of my Pushpin project
  version: "1.0"
  rapydo: 0.7.1

variables:

  env:

    FRONTEND_FRAMEWORK: angular

    ALCHEMY_USER: sqluser
    ALCHEMY_PASSWORD: chooseapasswordwisely

    ACTIVATE_ALCHEMY: 1
    ACTIVATE_POSTGRES: 1
    ACTIVATE_CELERY: 1
    ACTIVATE_MONGODB: 1
    ACTIVATE_PUSHPIN: 1
    CELERY_BACKEND: MONGODB
    CELERY_BACKEND_HOST: mongo.dockerized.io
    CELERY_BACKEND_PORT: 27017

  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user