---
project:
  title: My Celery project
  description: Title of my celery project
  version: "1.0"
  rapydo: 0.7.3

variables:

  env:

    FRONTEND_FRAMEWORK: angular
    AUTH_SERVICE: sqlalchemy

    ACTIVATE_ALCHEMY: 1
    ACTIVATE_POSTGRES: 1
    ACTIVATE_CELERY: 1
    ACTIVATE_RABBIT: 1
    ACTIVATE_REDIS: 1
    ACTIVATE_CELERYBEAT: 1
    CELERY_BACKEND: REDIS 

  backend:
    credentials:
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user
