version: '3'
#######################
# Link services inside API

services:
  proxy:
    environment:
      ACTIVATE: 1
    depends_on:
      - backend
      - frontend

  backend:
    environment:
      APP_MODE: production
      NGINX_ACTIVE: "True"

    networks:
      worker_net:
      proxy_net:
        aliases:
          - ${FLASK_HOST}

  frontend:
    environment:
      APP_MODE: production
      BACKEND_PORT: ${PROXY_PROD_PORT}
    networks:
      proxy_net:
        aliases:
          - html