---
project:
  title: My Sql project
  description: Title of my sql project
  version: "1.0"
  rapydo: 0.7.0

variables:

  submodules:
    utils:
      branch: 0.6.7
    http-api:
      branch: 0.6.7
    do:
      branch: 0.6.7

  env:

    BACKEND_BUILD_MODE: backendcentos

    ACTIVATE_ALCHEMY: 1
    ACTIVATE_POSTGRES: 1
    ALCHEMY_USER: sqluser
    ALCHEMY_PASSWORD: chooseapasswordwisely

  backend:
    credentials:
      username: "user@nomail.org"
      password: "test"
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user
  frontend:
    framework: angular
