---
project:
  title: My Sql project
  description: Title of my sql project
  version: "1.0"
  rapydo: 0.7.3

variables:

  env:

    FRONTEND_FRAMEWORK: angular
    AUTH_SERVICE: sqlalchemy

    BACKEND_BUILD_MODE: backendcentos

    ACTIVATE_ALCHEMY: 1
    ACTIVATE_POSTGRES: 1

  backend:
    credentials:
      roles:
        user: normal_user
        internal: staff_user
        admin: admin_root
        default: normal_user
